# The current file tells Conda and Binder which Jupyter packages to load at startup
name: emet2007
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - statsmodels
